name: CI Workflow with Email Step

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 21f3001194@ds.study.iitm.ac.in
        run: echo "Hello, world!"
